// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsekmacyykziphlzglmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzZWttYWN5eWt6aXBobHpnbG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwNDUxMTAsImV4cCI6MjA3OTYyMTExMH0.f2XnWaY5fzH44MTH51ccMo-sc9qqcpkdOzzYatAUfio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});